### ISSUE TITLE
Future 6.0 5.0

### ISSUE THREAD

**Issue by Eccleria** [Eccleria/ewibot#95]
What to be expected on 5.0 update. 

# https://github.com/Eccleria/ewibot/labels/remove
- [x] #134 
- [x] #139 DM Ewibot

# https://github.com/Eccleria/ewibot/labels/update Misc
## Personalities
- [x] #140 now in #156
- [x] Explode file into `Admin` #156 
- [x] Define log color in personality **canceled**

## Commons
- [x] regroup common values into `common` named object #138 

## Pronouns
- [x] change `buttonHandler` into more specific function name #101 ***now dispatch button action between corresponding purpose***

## Logs
- [x] Add author of pinning message #159 

## db
- [x] explode in multiple files #153 
- [x] use `db` as first argument for all helpers #153 

# Finish
## https://github.com/Eccleria/ewibot/labels/await 
- [x] #33 **deprecated** see #139 
- [x] #51 **merged in master in 4.8.0** see [changes](https://github.com/Eccleria/ewibot/compare/4.7.0...4.8.0)

### `/` Slash Commands
Ewibot Messages
- [x] channel 7b93083aaa75e1dd957f8337388f4c4dc9012a7c #139 
- [x] reply 7b93083aaa75e1dd957f8337388f4c4dc9012a7c #139 

# https://github.com/Eccleria/ewibot/labels/feat Misc
## Ewibot Status
- [x] Add `reading La Quête d'Ewilan` status #115 

## Polls
- [x] #129 #141

**Comment by Eccleria** [comment]
Completed in #177
